projects:
  heightshandyman:
    schemaPath: src/Contact/graphql/schema.json
    includes:
      - src/Contact/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
